### ISSUE TITLE
Balık geldiğini duyuyor tutuyor ama çekmiyor

### ISSUE THREAD

**Issue by UtkuDenizAltiok** [ucandutch/CaptainHook#1]
Selamlar güzel bot eline sağlık da balık geldiğini duyuyor tutuyor ama çekmiyor sarmıyor yani oltayı, bazen de durup dururken yürümeye çalışıyor balığı bozuyor tutmayı bırakıyor ne yapmak lazım ? Acaba oyun ayarları mı önemli

**Comment by ucandutch** [comment]
Birçok sebebi olabilir ama sanırım tam ekran sorunu ve Olta Atılan Nokta ayarında problem var. Tavsiyem tüm ayarları sıfırlaman. En kolay yolu uygulamayı silip yüklemen olur eğer istemiyorsan da tüm "tick" içeren ayarları açıp kapatman, örn. *Pathfinder ayarını aç ardından kapat. Bunu yaptıktan sonra uygulamayı sağ üstteki X tuşundan kapatıp açman da önemli. Böylece ayarlar kaydedilir birsonraki açılışta ayarlar hatırlanır ve problem ortadan kalkar. 
Tüm bunları yapınca yürüme sistemi devre dışı kalır. 

İkinci problemi de çözmen için tavsiyen önce sakin bi noktaya gitmen, kendi adan varsa ayar kontrolü için en ideali olur. Adada bi noktada karakteri suya yakın noktada durdur ve uygulamayı başlatmadan önce Olta Atılan Nokta kısmındaki yeşil "Refresh" butonuna bas. 
Bu semi-transparan bi ekran oluşturup ardından tıkladığın noktanın konumunu kaydeder ve bundan sonra balık oltalarını sadece bu noktaya atar. (Pathfinder kapalı olduğu sürece.) 

Not: Uygulamanın hâlâ bazı eksikleri var, kabul ediyorum. Üzerinde fazla çalışacak zamanım olmadı. Ama spesifik bir isteğin olursa ve vaktim olursa ekleyebilirim. Yine de bir sorun olursa, buradan sorup yardım alabilirsin.

Şimdiden kolay gelsin, rastgele!

**Comment by UtkuDenizAltiok** [comment]
> Birçok sebebi olabilir ama sanırım tam ekran sorunu ve Olta Atılan Nokta ayarında problem var. Tavsiyem tüm ayarları sıfırlaman. En kolay yolu uygulamayı silip yüklemen olur eğer istemiyorsan da tüm "tick" içeren ayarları açıp kapatman, örn. *Pathfinder ayarını aç ardından kapat. Bunu yaptıktan sonra uygulamayı sağ üstteki X tuşundan kapatıp açman da önemli. Böylece ayarlar kaydedilir birsonraki açılışta ayarlar hatırlanır ve problem ortadan kalkar. Tüm bunları yapınca yürüme sistemi devre dışı kalır.
> 
> İkinci problemi de çözmen için tavsiyen önce sakin bi noktaya gitmen, kendi adan varsa ayar kontrolü için en ideali olur. Adada bi noktada karakteri suya yakın noktada durdur ve uygulamayı başlatmadan önce Olta Atılan Nokta kısmındaki yeşil "Refresh" butonuna bas. Bu semi-transparan bi ekran oluşturup ardından tıkladığın noktanın konumunu kaydeder ve bundan sonra balık oltalarını sadece bu noktaya atar. (Pathfinder kapalı olduğu sürece.)
> 
> Not: Uygulamanın hâlâ bazı eksikleri var, kabul ediyorum. Üzerinde fazla çalışacak zamanım olmadı. Ama spesifik bir isteğin olursa ve vaktim olursa ekleyebilirim. Yine de bir sorun olursa, buradan sorup yardım alabilirsin.
> 
> Şimdiden kolay gelsin, rastgele!

Tam ekran sorunundan kastın ne tam olarak? Nokta kaydetmeyi vs düzgün yapıyorum aslında ama bazen öyle durup yürümeye başlıyor. Hani ilk önce 10 15 balık tutuyor sonra bozuluyor kapatıp açmam gerekiyor gibi

**Comment by ucandutch** [comment]
Balık tutmada bir sorun yaşamıyorsan şöyle dene, balık tutulacak noktayı karaktere yakın tut ve balık tutarken ses ekranını açık bırak. Sanırım olta sesinden başka bir ses duyunca olta ile aynı ses yüksekliğinde olunca balık tutmaya çalışıyo olabilir. Ses ekranını kontrol ederek gerekli ses seviyesi düzeltmelerini yapabilirsin. Eğer hala tüm bunlara rağmen yürümeye devam ediyorsa başka bir bug olabilir. Eğer yürüyorsa botu hiç durdurma ve izlemeye devam et. Karakter yürüdükten sonra 30sn olta gelmezse zaten yine durup olta atacaktır yani tutmaya devam edecektir. Bunun yapılabilmesi için karakter tabiki yürüdükten sonra suya tıklayabiliyor olmalı o yüzden oltayı karaktere çok uzak bir noktaya attırmaman önemli.

**Comment by UtkuDenizAltiok** [comment]
Yok balık tutmaya çalışmıyor sesten sorun yok bence ama mesela balığı çekerken çekme bitti balığı tuttu diyelim sanki orada bi süre çekmeye devam ediyor balığı tutmasına rağmen o sırada yürümeye başlıyıp bozuluyor. 

Bir de bende menü biraz bozuk bazı yerleri boşluklu tam gözükmüyor falan belki çözünürlükte sorun vardır

**Comment by UtkuDenizAltiok** [comment]
> Balık tutmada bir sorun yaşamıyorsan şöyle dene, balık tutulacak noktayı karaktere yakın tut ve balık tutarken ses ekranını açık bırak. Sanırım olta sesinden başka bir ses duyunca olta ile aynı ses yüksekliğinde olunca balık tutmaya çalışıyo olabilir. Ses ekranını kontrol ederek gerekli ses seviyesi düzeltmelerini yapabilirsin. Eğer hala tüm bunlara rağmen yürümeye devam ediyorsa başka bir bug olabilir. Eğer yürüyorsa botu hiç durdurma ve izlemeye devam et. Karakter yürüdükten sonra 30sn olta gelmezse zaten yine durup olta atacaktır yani tutmaya devam edecektir. Bunun yapılabilmesi için karakter tabiki yürüdükten sonra suya tıklayabiliyor olmalı o yüzden oltayı karaktere çok uzak bir noktaya attırmaman önemli.

![sa](https://github.com/user-attachments/assets/0d4c795b-4ea1-47ba-89b0-5452ae078fba)


Bak böyle bir hale bürünüyor 5 10 dk sonra uygulama sonra da bozulmalar başlıyor, tutamıyor tutarsa saramıyor sararsa sardıktan sonra yürüyor falan

**Comment by ucandutch** [comment]
Bilgisayar donanımın nedir özellikle işlemcin? Herhangi bir ısınma veya zorlanma problemi yaşıyor musun uygulamayı kullanırken? Çünki uygulama uygulama dosyalarını kullanan bir Hile/Hack olmadığı için bir kullanıcı gibi ekran okuma ve dinleme, klavye mouse  simülasyonuyla çalışıyor. Eğer cihaz tüm bunların kombine bir şekilde kullanılmasını destekleyemiyorsa da bu sorunu yaşayabilirsin. Tahminim de 5-10dk kullanabilmenden geçiyor. Uygulamada 5-10-15 vs dakikalarda herhangi bir ekstra komut yok. Eğer ilk 1 dakika çalışıyorsa sonraki sürelerde de aynı şekilde çalışmalı teknik olarak ki test yaptığım veya yaptırdığım tüm cihazlarda neredeyse 6-10 saatlik devamlı kullanım sağlayabildim. Eğer karakter yürür, duraksar veya herhangi bir hataylar karşılaşırsa "Olta Süresi" ayarındaki rakam (35 Saniye) sonunda oltada olup olmadığını kontrol edip, değilse yine en başa dönüp olta atmalı. Bunu da tabiki Olta atış noktası suya temas eden bir noktaysa yapabilir. Tüm bunlara rağmen hala çalışmıyorsa yüksek ihtimalle program yeterli işletim gücünü alamıyor olabilir. Ekran okuma özellikle biraz fazla bilgisayar gücü gerektiren bir işlem.

Lütfen cihaz özelliklerini burdan yaz ve uygulamayı açmadan önce oyun açıkken bir program sayesinde (ör. Msi Afterburner) ısı değerleri ve CPU kullanımı gibi detayları test yaparak buraya yine yaz. 

Teşekkürler.

**Comment by UtkuDenizAltiok** [comment]
Aslında bilgisayarımın iyi olması lazım hocam ya i7 11800h ve gtx3070 li gaming laptop kullanıyorum albionda hiç bir performans sorunu yaşamadım.  Benim ekran default çözünürlülüğü 2560x1440 acaba sorun bundan olabilir mi siz kodu hangi çözünürlük için yazdınız? 

Yeni bir commit yapmışsınız ne değiştirdiniz ?

Edit : Bu arada şeyi fark ettim bozulduğunda uygulama bu şekilde bi hal alıyor ve mouse basılı kalıyor çünkü mouse u hareket ettirdiğimde tıklamadan direk oraya doğru yürümeye başlıyor sanki mouse basılı kalmış gibi sürüklediğim yere otomatik yürümeye başlıyor
![as](https://github.com/user-attachments/assets/fc60f488-c318-48a8-830b-54518f22d554)

**Comment by ucandutch** [comment]
Hahahah sanırım sorunu anladım. Yeşil renk yani mapdeki çimler problem yaratıyor olabilir. Uygulamayı sağ üstteki butondan güncellemeni tavsiye ederim butona bir kez basıp 1-2 dakika beklemen yeterli olur kapatıp açtığında yeni halini kullabilirsin. Uygulama içinde yenilikler hakkında bir button da ekledim yine sağ üste. 
Şimdi gelelim soruna ve çözüme; 
Uygulama dediğim gibi ekran okuma sistemi üzerine çalışıyor ve Balık tutma ekranındaki yeşil pixelleri algılayıp ona göre Tıka-Bırak sistemi kullanıyor. Yani eğer kullandığın alan-map yeşil tonları ağırlıklı maplerse ki test yaparken açıkcası şu an resimde gördüğüm kadar yeşil bir alanda balık tutmamıştım. Yani yapılması gereken benim tarafımdan kodlarda yeşil pixel yakalama %sini değiştirmek olacak sanırım. Sana tavsiyem şimdilik daha farklı tonlarda bir map daha doğrusu çim yoğunluğunun bu kadar olmadığı bir alan kullanman. Mist ve Bridgewatch gibi.
Çözünürlük konusuna gelince 1920-1080de yazıldı program ama genel olarak tüm çözünürlüklerde kullanılabilir olması için Genel  pixel ve oran hesabıyla ekrandaki konumlar kullanılıyor ve okunuyor. Teknik olarak çözünürlükle alakalı bir problem olduğunu düşünmüyorum ama denemenden zarar gelmez. Çözünürlüğü değiştirip tekrar dene, Grafik ayarlarını en düşüğe almanı tavsiye ederim ve tüm bunlara rağmen hala çözülmediyse başka bir map dene. 

Umarım bunlarla sorun çözülür, ben de bu taraftan müsait olunca elimden geldiğince bi fix yapıp sürümü yine yenilerim. 
İyi oyunlar.

**Comment by UtkuDenizAltiok** [comment]
Hocam bot daha güzel olmuş elinize sağlık da, seaweed salad yeme butonu aktif olmuyor ya
